# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-ACH
version:      0.04
version_from: 
installdirs:  site
requires:
    ExtUtils::MakeMaker:           5.41
    Tk:                            402.002

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
